---
# tasks file for roles/meraki_env_ansible_valid

  - name: Check Meraki API Environment Variables
    loop:
    - MERAKI_KEY
    ansible.builtin.assert:
      that: lookup('env', item)
      fail_msg: ❌ Please set environment variable {{ item }}
      success_msg: ✅ {{ item }}


  - name: Check Meraki Module Variables
    loop:
    - meraki_org_name
    ansible.builtin.assert:
      that:
      - lookup('ansible.builtin.vars', item) is defined
      fail_msg: ❌ {{ item }} is not defined
      success_msg: ✅ {{ item }} is defined
