---
- name: Patch ISE Nodes to ISE 3.1 Patch 4
  hosts: ise
  gather_facts: no
  vars_files: vars/main.yaml
  roles:
    - role: ise_facts_standalone
      run_once: yes
    - role: ise_facts_table
      run_once: yes

    - role: ise_repository
      vars:
        repo_name: "{{ lookup('env','ISE_REPOSITORY') }}"
        repo_protocol: "{{ lookup('env','ISE_REPOSITORY_PROTOCOL') }}"
        repo_server: "{{ lookup('env','ISE_REPOSITORY') }}"
        repo_path: "{{ lookup('env','ISE_REPOSITORY_PATH') }}"
        repo_username: "{{ lookup('env','ISE_REPOSITORY_USERNAME') }}"
        repo_password: "{{ lookup('env','ISE_REPOSITORY_PASSWORD') }}"

    - role: ise_patch
      vars:
        repository_name: "{{ lookup('env','ISE_REPOSITORY') }}"
        patch_filename: ise-patchbundle-3.1.0.518-Patch4-22091704.SPA.x86_64.tar.gz

- name: Patch Complete!
  hosts: localhost
  gather_facts: no
  vars_files: vars/main.yaml
  roles:
    - role: ise_facts_standalone
    - role: ise_facts_table
    - role: banner # 💡 Not supported with `strategy: free`
