---
#------------------------------------------------------------------------------
# To use the `aws_ec2` dynamic inventory plugin, add this entry to the
# ansible.cfg file's [defaults] section :
#   [defaults]
#   inventory=inventory/aws_ec2.yaml
# ⚠ This file must end with `aws_ec2.y[a]ml`
#
# You may verify that it works with the command
#   `ansible-inventory --graph [-i inventory/aws_ec2.yaml]`
#
# For more examples, see
# https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ec2_inventory.html
#------------------------------------------------------------------------------

plugin: amazon.aws.aws_ec2

# aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY') }}"
# aws_secret_key: "{{ lookup('env','AWS_SECRET_KEY') }}"

# 💡 List your region(s) explicitly! Searching all regions takes 10X longer!
regions:
  # - eu-north-1
  # - ap-south-1
  # - eu-west-3
  # - eu-west-2
  # - eu-west-1
  # - ap-northeast-3
  # - ap-northeast-2
  # - ap-northeast-1
  # - sa-east-1
  # - ca-central-1
  # - ap-southeast-1
  # - ap-southeast-2
  # - eu-central-1
  # - us-east-1
  # - us-east-2
  - us-west-1
  # - us-west-2

filters:
  # tag:project: ise_pnp    # ⚠ You cannot use a variable here! "{{ project_name }}"
  # instance-state-name: ['running']
  # tag:application: ise

strict: False

keyed_groups:
  - key: instance_type
    # prefix: instance_type
    separator: ""
  - key: placement.region # group per region e.g. aws_region_us_east_2
    # prefix: region
    separator: ""
  - key: placement.availability_zone
    # prefix: az
    separator: ""
  - key: placement.group
    # prefix: group
    separator: ""
  - key: tags.application # or tags['application']
    # prefix: application
    separator: ""
  - key: tags.environment # or tags['environment']
    prefix: environment
    separator: "_"
  - key: tags.product # or tags['product']
    prefix: product
    separator: "_"
  - key: tags.project # or tags['project']
    # prefix: project
    separator: ""
  - key: tags.roles
    prefix: role
    separator: "_"
  - key: tags.services
    prefix: service
    separator: "_"

# List in order of precedence for `inventory_hostname` variables
hostnames:
  - tag:Name
  - ip-address
  - dns-name
# - private-ip-address

# Set individual variables with compose
compose:
  ansible_host: public_ip_address # Use private IP address to connect to the host
  # ansible_host: private_ip_address  # Use private IP address to connect to the host
  # inventory_hostname: private_ip_address  # Use private IP address to connect to the host
  # ansible_host: name  # Use name to connect to the host
  # ansible_host: public_dns_name
