---
#------------------------------------------------------------------------------
# Standalone ISE Node
# See https://cs.co/ise-aws for available AWS Instance Types and hourly rates
#------------------------------------------------------------------------------

ise_nodes:
  - name: ise-1
    ami: "{{ ise_image }}"
    # ami: ami-0c59bbc144f97a440 # us-west-1 ISE 3.2.0.542 20221002
    instance_type: "{{ ise_instance_type_default }}" # Evaluation/Demo only
    volume_size: 300
    private_ip: 172.31.2.11
    security_group: "{{ ise_security_group_default }}"
    tags:
      Name: ise-1
      data_class: public # [Public, Confidential, Highly confidential]
      business_unit: ENCC
      application: ise
      environment: demo # [Demo, Prod, Dev, QA, Stage, Test]
      owner: "{{ owner }}" # Owner of the application, workload, or service
      team: TME
      project: "{{ project_name }}"
      roles: # use [] (no roles) for dedicated PSN. Default: Standalone
        - Standalone  # default
      services: # use [] (no services) for dedicated PAN/MNT. Default: [Profiler, Session]
        - Profiler  # default
        - Session   # default
      started: "{{ '%Y-%m-%dT%H:%M:%S-%Z' | strftime }}"

    # roles:       # use [] (no roles) for dedicated PSN
    # - Standalone  # default
    # - PrimaryAdmin
    # - PrimaryMonitoring
    # - SecondaryAdmin
    # - SecondaryMonitoring
    # - PrimaryDedicatedMonitoring
    # - SecondaryDedicatedMonitoring
    # services:    # use [] (no services) for dedicated PAN/MNT
    # - DeviceAdmin
    # - Profiler # default
    # - Session  # default
    # - pxGrid
    # - pxGridCloud
    # - PassiveIdentity
    # - SXP
    # - TC-NAC
