---
# tasks file for roles/ise_cli_reload

#----------------------------------------------------------------------------
# This is an example of the reload command execution:
#
#   ise/admin#reload
#   Save the current ADE-OS running configuration? (yes/no) [yes] ? yes
#   Generating configuration...
#   Saved the ADE-OS running configuration to startup successfully
#
#   Broadcast message from root@ise (pts/1) (Sun Oct  9 15:14:28 2022):
#
#   Trying to stop processes gracefully. Reload might take approximately 3 mins
#----------------------------------------------------------------------------
# This is what anyone on the console will see when this is run:
#   ise/admin#
#
#   Broadcast message from root@ise (pts/1) (Sun Oct  9 14:57:37 2022):
#
#   Trying to stop processes gracefully. Reload might take approximately 3 mins
#----------------------------------------------------------------------------
# Timing:
# 6 minutes for HTTP to enable
# 16 minutes for a application server initialization

#----------------------------------------------------------------------------
# ✅ Without registering any output?
#----------------------------------------------------------------------------
- name: Reload ISE | {{ inventory_hostname }}
  vars:
    # 💡 The `reload` command requires ~7 minutes to work!
    #  ⚠ A timeout of less than 7 x 60 seconds will result in a failure!
    ansible_command_timeout: 600
  ansible.netcommon.cli_command:
    command: reload
    check_all: yes # run all of the commands
    sendonly: no
    newline: yes
    prompt:
      # Save the current ADE-OS running configuration? (yes/no) [yes] ?
      - Save the current ADE-OS running configuration
      # Continue with reboot? [y/n]
      - Continue with reboot
      # Trying to stop processes gracefully. Reload might take approximately 3 mins
      # - Trying to stop processes gracefully
    answer:
      - "yes"
      - "y"
      # - "\r"
  register: out

- ansible.builtin.debug:
    msg: "{{ out.stdout | replace('\n\n','\n') }}"

# - name: Wait 5 minutes before continuing...
#   delegate_to: localhost
#   ansible.builtin.wait_for:
#     timeout: 300

# - name: ISE CLI | {{ inventory_hostname }} | {{ cmd }}
#   ansible.netcommon.cli_command:
#     command: application start ise
#   register: out

# - ansible.builtin.debug:
#     msg: "{{ out.stdout | replace('\n\n','\n') }}"

# - name: Reset the Connection
#   meta: reset_connection

- name: Exit | {{ inventory_hostname }}
  ansible.netcommon.cli_command:
    command: "exit"
