---
- block:

  - name: Enable ISE OpenAPIs (ISE 3.1+)
    delegate_to: localhost
    ansible.builtin.uri:
      url: "https://{{ ansible_host }}/admin/API/apiService/update"
      method: POST
      url_username: "{{ ise_username }}"
      url_password: "{{ ise_password }}"
      force_basic_auth: yes
      body: '{ "papIsEnabled":true, "psnsIsEnabled":true }'
      status_code: 200,500
      body_format: json
      validate_certs: "{{ ise_verify }}"
      return_content: true
    register: response
    failed_when: (response.status != 200) and (response.status != 500)
    ignore_errors: yes # Errors do not stop execution

  # - name: response
  #   ansible.builtin.debug: var=response

  - name: Enable ISE ERS APIs
    delegate_to: localhost
    ansible.builtin.uri:
      url: "https://{{ ansible_host }}/admin/API/NetworkAccessConfig/ERS"
      method: PUT
      url_username: "{{ ise_username }}"
      url_password: "{{ ise_password }}"
      force_basic_auth: yes
      headers:
        Accept: application/xml
        Content-Type: application/xml
      body: '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ersConfig>
    <id>1</id><isCSRFCheck>false</isCSRFCheck><isPapEnabled>true</isPapEnabled><isPsnsEnabled>true</isPsnsEnabled></ersConfig>'
      status_code: 200
      validate_certs: "{{ ise_verify }}"
      return_content: true
    register: response
    failed_when: response.status != 200

  rescue:

  # - name: response
  #   ansible.builtin.debug: var=response

  - name: 401 - Wrong Password?
    when: response.status == 401
    ansible.builtin.debug:
      msg : "🛑 Please verify your ISE admin password to enable ISE APIs"

