---

ssh_key_directory: ~/.ssh
ssh_key_name: "{{ project_name }}"
ssh_key_passphrase: "{{ project_name }}"
ssh_key_private_file: "{{ ssh_key_directory }}/{{ ssh_key_name }}"
ssh_key_public_file: "{{ ssh_key_private_file }}.pub"

ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_ssh_user: admin
# ansible_ssh_pass: C1sco12345
#
# When running playbooks requiring an SSH connection secured by SSH keys,
# you must specify `--ask-pass` on the playbook command line to be
# prompted for your private key passphrase.
#
ansible_ssh_private_key_file: "{{ ssh_key_private_file }}"

